config/routes.rb
Rails.application.routes.draw do

  get 'order_report/index', to: "order_report#index"
  post 'order_report', to: "order_report#index"

  resources :order_items
  get 'employee_report', to: "employee_report#index"
  post 'employee_report', to: "employee_report#index"

  get 'sales_report', to: "sales_report#index"
  post 'sales_report', to: "sales_report#index"



  devise_for :users, :path_prefix => 'd', :skip => [:registrations]
  devise_scope :user do
    authenticated do
      root to: 'admin#index'
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: 'unauthenticated_root'
    end
  end

  get 'admin' => 'admin#index'

  # controller :sessions do
  #   get 'login' => :new
  #   post 'login' => :create
  #   delete 'logout' => :destroy
  # end

  resources :users
  resources :products
  resources :employees
  resources :orders

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord

  # has_many :orders
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :pay_scale)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :employee_name %>
  </div>

  <div class="field">
    <%= form.label :pay_scale %>
    <%= form.text_field :pay_scale, id: :employee_pay_scale %>
  </div>
<br>
  <div class="actions">
    <%= form.submit nil, :class => 'submit' %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<br>
<h3>Editing Employee</h3>
<div class="box">

<b><%= render 'form', employee: @employee %></b>

<%= link_to '<button id="new"> Show </button>' .html_safe, @employee %> &nbsp;&nbsp;&nbsp;
<%= link_to '<button id="new"> Back </button>' .html_safe, employees_path %>
</div>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Employees</h3>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Pay Scale</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= number_to_currency employee.pay_scale %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Delete', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '<button id="new">New Employee</button>'.html_safe, new_employee_path %>




<p id="notice"><%= notice %></p>

app/views/employees/new.html.erb
<br>
<h3>New Employee</h3>
<div class="box">

  <b><%= render 'form', employee: @employee %></b>

<%= link_to '<button id="back">Back</button>'.html_safe, employees_path %>
</div>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>
<h3>Employee</h3>

<div class="box">

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Pay scale:</strong>
  <%= number_to_currency (@employee.pay_scale) %>
</p>

<br>
<%= link_to '<button id="new"> Edit </button>' .html_safe, edit_employee_path(@employee) %> &nbsp;&nbsp;&nbsp;
<%= link_to '<button id="new"> Back </button>' .html_safe, employees_path %>

</div>>