config/routes.rb
Rails.application.routes.draw do

  get 'order_report/index', to: "order_report#index"
  post 'order_report', to: "order_report#index"

  resources :order_items
  get 'employee_report', to: "employee_report#index"
  post 'employee_report', to: "employee_report#index"

  get 'sales_report', to: "sales_report#index"
  post 'sales_report', to: "sales_report#index"



  devise_for :users, :path_prefix => 'd', :skip => [:registrations]
  devise_scope :user do
    authenticated do
      root to: 'admin#index'
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: 'unauthenticated_root'
    end
  end

  get 'admin' => 'admin#index'

  # controller :sessions do
  #   get 'login' => :new
  #   post 'login' => :create
  #   delete 'logout' => :destroy
  # end

  resources :users
  resources :products
  resources :employees
  resources :orders

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coffee_Project</title>
  <%= csrf_meta_tags %>

  <link href='http://fonts.googleapis.com/css?family=Lobster+Two' rel='stylesheet' type='text/css'>
  <!--bootstrap -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>


    <script type="text/javascript">
      function changecolor(color){
           document.getElementsByTagName('body')[0].style.
               backgroundColor=color.value;
        }
    </script>

    <div class="one">
      <!--<img src="https://png.pngtree.com/element_origin_min_pic/16/09/23/1257e4b57685460.jpg" align="left" width="100px" height="100" border="2px">-->
      <center><h2>Coffee Ordering System</h2></center>

    </div>
    <div class="two">
      <ul><center>
        <li class="home"><b><%= link_to image_tag("home.png", width: '20px') + " Home", admin_path%></b></li>

        <li><b><%= link_to image_tag("new.png", width: '20px') + " New Order", new_order_path%></b></li>
        <li><b><%= link_to image_tag("order.png", width: '20px') + " Review Orders", orders_path%></b></li>
        <li><b><%= link_to image_tag("menu.png", width: '20px') + " Menu", products_path%></b></li>
<!--        <li><b><%#= link_to "Order Items", order_items_path%></b></li>-->

          <% if current_user.try(&:manager) %>
          <li><b><%= link_to image_tag("employee.png", width: '20px') + " Employees", employees_path%></b></li>
          <li><b><%= link_to image_tag("sale.png", width: '20px') + " Sales", order_report_index_path%></b></li>
          <li><b><%= link_to image_tag("user.png", width: '20px') + " Users", users_path%></b></li>
          <% end %>
        <% if user_signed_in? %>
            <li class="logout"><b><%= link_to image_tag("login.png", width: '20px') + " Logout", destroy_user_session_path, method: :delete %></b></li>
            <!--          <li class="logout"><b><%#= link_to 'Logout', destroy_user_session_path, method: :delete %></b></li>-->
        <% else %>
            <li class="login"><b><%= link_to image_tag("login.png", width: '20px') + " Login", new_user_session_path%></b></li>
            <!--          <li class="login"><b><%#= link_to 'Login', new_user_session_path %></b></li>-->
        <% end %>
      </center>
      </ul></div>

<body>
<div class="rubybodycontainer">
  <%= yield %>

<br><br><br><br>

</div>
</body>

<footer>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</footer>
</html>